---
apiVersion: v1
kind: Namespace
metadata:
  name: boardgame-api
  labels:
    name: boardgame-api

---
kind: Service
apiVersion: v1
metadata:
  name: api-auth
  labels:
    app: api-auth
spec:
  clusterIP: 10.96.0.54
  ports:
    - protocol: TCP
      targetPort: 80
      port: 80
  selector:
    app: api-auth

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: api-auth
  labels:
    app: api-auth
  namespace: boardgame-api
spec:
  replicas: 2
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: api-auth
  template:
    metadata:
      labels:
        app: api-auth
    spec:
      containers:
        - name: api-auth
          image: david511382/boardgame_auth.api:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: "MEMBERDBCONFIG"
              value: "Server=10.96.0.11;Initial Catalog=BoardGameMember;Persist Security Info=True;User ID=AuthWebService;Password=auth$WebService;TrustServerCertificate=False;"
            - name: "CONNECTIONSSTRINGS_ELASTICSEARCHSERVERADDRESS"
              value: "http://10.96.0.92:9200"