---
apiVersion: v1
kind: Namespace
metadata:
  name: boardgame-ui
  labels:
    name: boardgame-ui

---
kind: Service
apiVersion: v1
metadata:
  name: ui-angular
  labels:
    app: ui-angular
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 9487
      nodePort: 30487
      targetPort: 80
  selector:
    app: ui-angular

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ui-angular
  labels:
    app: ui-angular
  namespace: boardgame-ui
spec:
  replicas: 3
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ui-angular
  template:
    metadata:
      labels:
        app: ui-angular
    spec:
      containers:
        - name: ui-angular
          image: david511382/boardgame_angular.ui:latest
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: "CONNECTIONSSTRINGS_BACKENDDOMAIN"
              value: "http://10.96.0.88:80"
            - name: "CONNECTIONSSTRINGS_ELASTICSEARCHSERVERADDRESS"
              value: "http://10.96.0.92:9200"