version: '3'
services:
  member.db:
    container_name: board-game-member-db
    image: mcr.microsoft.com/mssql/server:latest
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD="f#JF39F3jds"
    ports:
      - "1487:1433"
    volumes:
      - member-db-volume:/var/opt/mssql
    networks:
        board-game-network:
            ipv4_address: 172.54.87.10

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es01
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
     board-game-network:
            ipv4_address: 172.54.87.92
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.3.2
    container_name: es02
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata02:/usr/share/elasticsearch/data
    networks:
       board-game-network:
            ipv4_address: 172.54.87.93

  auth.api:
    container_name: board-game-auth-api
    build:
      context: .
      dockerfile: src/Services/Auth/AuthWebService/Dockerfile
    depends_on:
      - member.db
    networks:
         board-game-network:
            ipv4_address: 172.54.87.54

  auth.gw:
    container_name: board-game-auth-gw
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGateway/Dockerfile
    depends_on:
      - auth.api
    networks:
         board-game-network:
            ipv4_address: 172.54.87.88

  angular.ui:
    container_name: board-game-angular-ui
    build: ./src/WebUI/BoardGameAngular
    ports:
      - "9487:80"
    depends_on:
      - auth.gw
    networks:
         board-game-network:
            ipv4_address: 172.54.87.94

volumes:
  member-db-volume:
  esdata01:
    driver: local
  esdata02:
    driver: local

networks:
   board-game-network:
      ipam:
         config:
         - subnet: 172.54.87.0/24