version: '3.2'
services:
  member.db:
    container_name: board-game-member-db
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD="f#JF39F3jds"
    ports:
      - "1487:1433"
    volumes:
      - member-db-volume:/var/opt/mssql
    networks:
        board-game-network:
            ipv4_address: 172.54.87.10

  redis.master1:
    container_name: redis-master1
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    ports:
      - "6380:6379"
    networks:
         board-game-network:
            ipv4_address: 172.54.87.12
  redis.master2:
    container_name: redis-master2
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
            ipv4_address: 172.54.87.13
  redis.master3:
    container_name: redis-master3
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
            ipv4_address: 172.54.87.14
  redis.slave1:
    container_name: redis-slave1
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    command: redis-server --slaveof redis-master1 6379
    depends_on:
      - redis.master1
    networks:
         board-game-network:
            ipv4_address: 172.54.87.15
  redis.slave2:
    container_name: redis-slave2
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    command: redis-server --slaveof redis-master2 6379
    depends_on:
      - redis.master2
    networks:
         board-game-network:
            ipv4_address: 172.54.87.16
  redis.slave3:
    container_name: redis-slave3
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    command: redis-server --slaveof redis-master3 6379
    depends_on:
      - redis.master3
    networks:
         board-game-network:
            ipv4_address: 172.54.87.17

  redis.cluster-creator:
    container_name: redis-cluster-creator
    build:
      context: redis/createnode/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
    depends_on:
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3

  redis.sentinel1:
    container_name: redis-sentinel1
    build:
      context: redis/sentinel/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
    depends_on: 
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3
  redis.sentinel2:
    container_name: redis-sentinel2
    build:
      context: redis/sentinel/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
    depends_on: 
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3
  redis.sentinel3:
    container_name: redis-sentinel3
    build:
      context: redis/sentinel/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
    depends_on:
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3

  es01:
    container_name: es01
    build:
      context: ELK/Elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02:9300
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: bind
        source: ./ELK/Elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch01
        target: /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      board-game-network:
         ipv4_address: 172.54.87.92
  es02:
    container_name: es02
    build:
      context: ELK/Elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01:9300
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: bind
        source: ./ELK/Elasticsearch/config/elasticsearch.yml
        target: /usr/share/elasticsearch/config/elasticsearch.yml
        read_only: true
      - type: volume
        source: elasticsearch02
        target: /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      board-game-network:
        ipv4_address: 172.54.87.93
             
  kibana:
    build:
      context: ELK/Kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    volumes:
      - type: bind
        source: ./ELK/Kibana/config/kibana.yml
        target: /usr/share/kibana/config/kibana.yml
        read_only: true
    depends_on:
      - es01
    ports:
      - 5601:5601
    networks:
       board-game-network:
            ipv4_address: 172.54.87.50

  auth.api:
    container_name: board-game-auth-api
    build:
      context: .
      dockerfile: src/Services/Auth/AuthWebService/Dockerfile
    depends_on:
      - member.db
      - es01
    networks:
         board-game-network:
            ipv4_address: 172.54.87.54

  boardgame.gw:
    container_name: board-game-gw
    build:
      context: .
      dockerfile: src/ApiGateways/OcelotApiGateway/Dockerfile
    depends_on:
      - auth.api
      - es01
    networks:
         board-game-network:
            ipv4_address: 172.54.87.88

  angular.ui:
    container_name: board-game-angular-ui
    build:
      context: .
      dockerfile: src/WebUI/BoardGameAngular/dockerfile
    ports:
      - "9487:80"
    depends_on:
      - boardgame.gw
      - es01
    networks:
         board-game-network:
            ipv4_address: 172.54.87.94

volumes:
  member-db-volume:
  elasticsearch01:
  elasticsearch02:

networks:
   board-game-network:
      ipam:
         config:
         - subnet: 172.54.87.0/24