version: '3.2'
services:
  redis.master1:
    container_name: redis-master1
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    ports:
      - "6380:6379"
    networks:
         board-game-network:
            ipv4_address: 172.54.87.12
  redis.master2:
    container_name: redis-master2
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
            ipv4_address: 172.54.87.13
  redis.master3:
    container_name: redis-master3
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
            ipv4_address: 172.54.87.14
  redis.slave1:
    container_name: redis-slave1
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    command: redis-server --slaveof redis-master1 6379
    depends_on:
      - redis.master1
    networks:
         board-game-network:
            ipv4_address: 172.54.87.15
  redis.slave2:
    container_name: redis-slave2
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    command: redis-server --slaveof redis-master2 6379
    depends_on:
      - redis.master2
    networks:
         board-game-network:
            ipv4_address: 172.54.87.16
  redis.slave3:
    container_name: redis-slave3
    build:
      context: redis/node/
      args:
        REDIS_VERSION: $REDIS_VERSION
    command: redis-server --slaveof redis-master3 6379
    depends_on:
      - redis.master3
    networks:
         board-game-network:
            ipv4_address: 172.54.87.17

  redis.cluster-creator:
    container_name: redis-cluster-creator
    build:
      context: redis/createnode
      dockerfile: dockerfile
      args:
        REDIS_VERSION: $REDIS_VERSION
    environment:
     - REDIS_DOMAIN1=172.54.87.12:6379
     - REDIS_DOMAIN2=172.54.87.13:6379
     - REDIS_DOMAIN3=172.54.87.14:6379
     - REDIS_SLAVE_DOMAIN1=172.54.87.15:6379
     - REDIS_SLAVE_DOMAIN2=172.54.87.16:6379
     - REDIS_SLAVE_DOMAIN3=172.54.87.17:6379
    networks:
         board-game-network:
    depends_on:
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3

  redis.sentinel1:
    container_name: redis-sentinel1
    build:
      context: redis/sentinel/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
    depends_on: 
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3
  redis.sentinel2:
    container_name: redis-sentinel2
    build:
      context: redis/sentinel/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
    depends_on: 
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3
  redis.sentinel3:
    container_name: redis-sentinel3
    build:
      context: redis/sentinel/
      args:
        REDIS_VERSION: $REDIS_VERSION
    networks:
         board-game-network:
    depends_on:
      - redis.master1
      - redis.master2
      - redis.master3
      - redis.slave1
      - redis.slave2
      - redis.slave3

networks:
   board-game-network:
     ipam:
       config:
       - subnet: 172.54.87.0/24