// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations.Game
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DAL.Models.GameInfo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateTime");

                    b.Property<string>("Description")
                        .HasMaxLength(200);

                    b.Property<int>("MaxPlayerCount");

                    b.Property<int>("MinPlayerCount");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ID", "Name");

                    b.ToTable("GameInfo");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CreateTime = new DateTime(2022, 8, 29, 11, 33, 16, 338, DateTimeKind.Local).AddTicks(863),
                            Description = "象棋遊戲",
                            MaxPlayerCount = 2,
                            MinPlayerCount = 2,
                            Name = "軍棋"
                        },
                        new
                        {
                            ID = 2,
                            CreateTime = new DateTime(2022, 8, 29, 11, 33, 16, 340, DateTimeKind.Local).AddTicks(4867),
                            Description = "撲克牌遊戲",
                            MaxPlayerCount = 4,
                            MinPlayerCount = 2,
                            Name = "大老二"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
