---
kind: Service
apiVersion: v1
metadata:
  name: db-member
  labels:
    app: db-member
spec:
  type: NodePort
  clusterIP: 10.96.0.11
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30433
  selector:
    app: db-member

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: db-member
  labels:
    app: db-member
  namespace: boardgame-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: db-member
  template:
    metadata:
      labels:
        app: db-member
    spec:
      terminationGracePeriodSeconds: 10
      containers:
        - name: db-member
          image: mcr.microsoft.com/mssql/server:latest
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "f#JF39F3jds"
          volumeMounts:
            - name: mssql-persistent-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-persistent-storage
          persistentVolumeClaim:
            claimName: mssql-data-claim