version: '3.2'
services:
  auth.api:
    container_name: board-game-auth-api
    build:
      context: ../../.
      dockerfile: src/Services/Auth/AuthWebService/Dockerfile
    networks:
         docker_board-game-network:
            ipv4_address: 172.54.87.54
  
  api.lobby:  
    container_name: api-lobby
    build:
      context: ../../.
      dockerfile: src/Services/Lobby/Dockerfile
    networks:
         docker_board-game-network:
            ipv4_address: 172.54.87.154

  api.game:  
    container_name: api-game
    build:
      context: ../../.
      dockerfile: src/Services/Game/GameWebService/Dockerfile
    networks:
         docker_board-game-network:
            ipv4_address: 172.54.87.178
            
  boardgame.gw:
    container_name: board-game-gw
    build:
      context: ../../.
      dockerfile: src/ApiGateways/OcelotApiGateway/Dockerfile
    depends_on:
      - auth.api
      - api.lobby
      - api.game
    networks:
         docker_board-game-network:
            ipv4_address: 172.54.87.88

  angular.ui:
    container_name: board-game-angular-ui
    build:
      context: ../../.
      dockerfile: src/WebUI/BoardGameAngular/dockerfile
    ports:
      - "9487:80"
    depends_on:
      - boardgame.gw
    networks:
         docker_board-game-network:
            ipv4_address: 172.54.87.94

networks:
   docker_board-game-network:
     external: true