version: '3.2'
services:
  member.db:
    container_name: board-game-member-db
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=f#JF39F3jds
    ports:
      - "1487:1433"
    volumes:
      - member-db-volume:/var/opt/mssql
    networks:
      board-game-network:


  db.game:
    container_name: db-game
    image: mcr.microsoft.com/mssql/server:2019-GA-ubuntu-16.04
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=f#JF39F3jds
    ports:
      - "1488:1433"
    volumes:
      - game-db-volume:/var/opt/mssql
    networks:
      board-game-network:


  redis.master:
    container_name: redis-master
    image: redis
    command: /config/redis.conf
    ports:
      - "6380:6379"
    volumes:
      - ./redis/node:/config
    networks:
      board-game-network:


  redis-commander:
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis.master:6379
      # - HTTP_USER=root
      # - HTTP_PASSWORD=root
    ports:
      - "8081:8081"
    depends_on:
      - redis.master
    networks:
      board-game-network:


  es01:
    container_name: es01
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02:9300
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: elasticsearch01
        target: /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      board-game-network:
        ipv4_address: 172.54.87.92
  es02:
    container_name: es02
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01:9300
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: elasticsearch02
        target: /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      board-game-network:
        ipv4_address: 172.54.87.93

  kibana:
    build:
      context: elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    depends_on:
      - es01
    ports:
      - 5601:5601
    networks:
      board-game-network:
        ipv4_address: 172.54.87.50

  api:
    build:
      context: ../../.
      dockerfile: src/API/BoardGameWebService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - 5283:80
    depends_on:
      - member.db
      - db.game
      - redis.master
      - es01
    networks:
      board-game-network:


  nginx:
    build:
      context: nginx/
      args:
        VERSION: 1.23
    ports:
      - 5282:80
    depends_on:
      - api
    networks:
      board-game-network:


  angular.ui:
    container_name: board-game-angular-ui
    build:
      context: ../../.
      dockerfile: src/WebUI/BoardGameAngular/dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    ports:
      - "9487:80"
    depends_on:
      - nginx
      - es01
    networks:
      board-game-network:
        ipv4_address: 172.54.87.94

volumes:
  member-db-volume:
  game-db-volume:
  elasticsearch01:
  elasticsearch02:


networks:
  board-game-network:
    ipam:
      config:
        - subnet: 172.54.87.0/24
