version: '3.2'
services:
  es01:
    container_name: es01
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=es01
      - discovery.seed_hosts=es02:9300
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: elasticsearch01
        target: /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      docker_board-game-network:
         ipv4_address: 172.54.87.92
  es02:
    container_name: es02
    build:
      context: elk/elasticsearch/
      args:
        ELK_VERSION: $ELK_VERSION
    environment:
      - node.name=es02
      - discovery.seed_hosts=es01:9300
      - cluster.initial_master_nodes=es01,es02
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - type: volume
        source: elasticsearch02
        target: /usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      docker_board-game-network:
        ipv4_address: 172.54.87.93
             
  kibana:
    container_name: kibana
    build:
      context: elk/kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    depends_on:
      - es01
    ports:
      - 5601:5601
    networks:
       docker_board-game-network:
            ipv4_address: 172.54.87.50

volumes:
  elasticsearch01:
  elasticsearch02:

networks:
   docker_board-game-network:
     external: true