#Depending on the operating system of the host machines(s) that will build or run the containers, the image specified in the FROM statement may need to be changed.
#For more information, please see https://aka.ms/containercompat

FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS base
WORKDIR /app
EXPOSE 80

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /src
COPY src/DAL/DAL.csproj  ./DAL/
COPY src/WebUI/BoardGameAngular/BoardGameAngular.csproj ./WebUI/BoardGameAngular/
COPY src/Common/Util/Util.csproj ./Common/Util/
COPY src/Common/Domain/Domain.csproj ./Common/Domain/

RUN dotnet restore ./WebUI/BoardGameAngular/BoardGameAngular.csproj

WORKDIR /src
COPY src/DAL/. ./DAL/
COPY src/WebUI/BoardGameAngular/. ./WebUI/BoardGameAngular/
COPY src/Common/Util/. ./Common/Util/
COPY src/Common/Domain/. ./Common/Domain/

WORKDIR /src/WebUI/BoardGameAngular
# Setup NodeJs
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y gnupg2 && \
    wget -qO- https://deb.nodesource.com/setup_10.x | bash - && \
    apt-get install -y build-essential nodejs
# End setup

WORKDIR /src/WebUI/BoardGameAngular
FROM build AS publish
RUN dotnet publish -c Release -o out

FROM base AS final
WORKDIR /app
COPY --from=publish /src/WebUI/BoardGameAngular/out .
ENTRYPOINT ["dotnet", "BoardGameAngular.dll"]