---
apiVersion: v1
kind: Namespace
metadata:
  name: boardgame-db
  labels:
    name: mssql

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mssql-data-claim
  namespace: boardgame-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi